eliminate parallelStream
fullstorydev/lucene-solr pull request #200
Opened 2022-11-03 08:01 UTC by noblepaul

while we were testing the RC1 for Solr 9.1 release, we observed that there is a significant slowdown in shutting down nodes. upon further investigation we realized that there were threads hanging in ForkJoinPool.commonPool

![forkjoinpool](https://user-images.githubusercontent.com/54862/199671560-b620bd84-eef4-488a-94bc-1379596b35f0.png)

2022-11-03 13:35 UTC, magibney requested changes
Thanks for catching this! I left a few questions/suggestions.

It's a little unsettling that `parallelStream()` resulted in threads actually hanging -- parallel being slower or unnecessary is one thing; hung threads is another! I wonder if it'd be worth pulling at that thread (independent of this change), since in principle it should be possible to invoke these operations in parallel, no?

EDIT: To more clearly demonstrate what I mean, I opened #201 against this branch; the diff against `release/8.8` is contained in the single commit: 2a044bbf96fa158ab4026059ed2dd90e2a2f9b3c

2022-11-03 13:35 UTC, magibney commented on solr/core/src/java/org/apache/solr/cloud/ZkController.java
> +        // Create a concurrently accessible set to avoid repeating collections
whitespace is a bit off -- entire method over-indented at the top level, makes review unnecessarily difficult

2022-11-03 13:35 UTC, magibney commented on solr/core/src/java/org/apache/solr/cloud/ZkController.java
> -        if (processedCollections.add(coll.getName()) && coll.isPerReplicaState()) {
Do we no longer care whether `coll.isPerReplicaState()`?

2022-11-03 13:35 UTC, magibney commented on solr/core/src/java/org/apache/solr/cloud/ZkController.java
> +            collectionsInThisNode.add(cd.getCloudDescriptor().getCollectionName());
I suspect that this fix could be done more succinctly by keeping the majority of existing code, with two changes:
1. parallelStream => stream
2. use `cd.getCloudDescriptor().getCollectionName()` to get collection name pre-deduping (as you've done here), deferring `zkStateReader.getCollection()` to ensure it's invoked only once per collection.

smaller diff in and of itself doesn't matter; but it serves to clarify what's actually changing, and reduces the likelihood of unnecessary future merge conflicts.

2022-11-03 13:35 UTC, magibney commented on solr/core/src/java/org/apache/solr/cloud/ZkController.java
> -      // Create a concurrently accessible set to avoid repeating collections
nit: remove "concurrently" from comment, as no longer applicable

2022-11-04 16:13 UTC, magibney commented
mostly LGTM. Formatting changes seem fine as they're mostly just pulled in from upstream, but it'd still be good to fix the over-indent.

To summarize, the substantial changes this introduces are: null check, swap parallelStream for serial forEach.

The only other thing that I definitely think should be adjusted (and fixed upstream too, unless I'm mistaken?) is to restore the conditional on `coll.isPerReplicaState()` -- as it stands this would create PRS entries for non-PRS collections, which even if they're ignored is probably not desirable.

2022-11-04 17:42 UTC, magibney commented
My preference would be to merge #201 into this branch and then merge into `release/8.8`.

2022-11-04 18:13 UTC, patsonluk approved these changes
LGTM!

2022-11-04 18:15 UTC, magibney approved these changes

2022-11-04 18:17 UTC, merged

2022-11-04 18:18 UTC, magibney commented
Thanks again for raising this, @noblepaul ! Went ahead with merging with the goal of getting this deployed asap.